# Generated by Django 4.0.6 on 2022-10-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('albumId', models.IntegerField()),
                ('url', models.CharField(default=0, max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('asd', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('albumId', models.IntegerField()),
                ('url', models.CharField(default=0, max_length=200)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('asd', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
