# Generated by Django 4.0.6 on 2022-10-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyTask', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='asd',
        ),
    ]
