# Generated by Django 4.0.6 on 2022-10-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlyTask', '0002_delete_photos_remove_photo_asd'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='color',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
